---
title: "Using R for Cyclodextrin Affinity Prediction"
output: html_notebook
---

Currently, this can only be used to predict for alpha- and beta-CD. Gamma-CD is still in the works. The value returned by the code is the change in Gibbs free energy (often abbreviated as dG of DelG) of guest-host complexation. 

The code used to actually build the models can be found in the repository [wip-cactus](https://github.com/awqx/wip-cactus). Don't mind the name -- it's a leftover from early steps in the QSAR building process. 

Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
