# Functions for implementing ensemble prediction with QSARs
install.packages("caret")
install.packages("Cubist")
install.packages("e1071")
install.packages("glmnet")
install.packages("kernlab")
install.packages("pls")
install.packages("randomForest")
library("caret")
library("Cubist")
library("e1071")
library("glmnet")
library("kernlab")
library("pls")
library("randomForest")
